import xlrd
import xlsxwriter

plain = "YCRKJVJNKRBCKIRKPOCCIQBKIYHCKNRBIQOKNKVVBKIKREBNKPICYCNBCDOCXHBOPBIWOYCEKOCINJKYNBCCXUKNRBIKPOKYNBCYCCCXBIOBQIBXBUKIYFCPBYBUBKIOVCDQHYKIRFKBRXCNVJKNBUHKIRUCNNDFYKIQPCUKIKRBKIVKIWBIQUCNFCNKYBCIBIXCNEDOKPPCXHCZCDNUCDIYNJICZNBOWORJBIQCXOYKNSKYBCIKNDECDNYHKYOEJBIBYBKPYHCDQHYKOBOZBYUHCXXEJNKRBCKNDECDNCNFCOOBVPJKHCKTFNCFKQKIRKBEDNEDNKITBCDOPJKOYHCDQHLDOYVJOKJBIQOCBEBQHYKPPKJEJRCDVYOYJFBUKPFCPBYBUBKIOFNCFKQKIRKVDYFDVPBUCFBIBCIQNKRDKPPJKVOCNVOBYKOKXKUYBIRBSBRDKPOOYKNYOYNDYYBIQKNCDIRZBYHOYCDYUPDVOXCCRQPCNBCDOXCCRBOKUCEECIUNJCUUKOBCIKPPJODIQYCVKNYOEDOBUZBYHCNRBIKNJHKNRZCNWBIQXCPWHKNKOOBIQCXXBUBKPOVCYHPCUKPKIRIKYBCIKPKIRUDNOBIQUKFBYKPBOYOKIRUKFYKBIOCXBIRDOYNJUCFOOHNBIWXNCEQCBIQCDYCIIBQHYOHBXYBIEKUCIKECVOYCNEOKEDIBUBFKPVDBPRBIQBINCUKRKECDNNDXXBKIONCVKHKIQKNXDPPCXXCCROYDXXOFBPPKQBIQYCIOCXYDIKXBOHEBPWKIRUCUCKKOKPOCKSKOYGDKIYBYJCXUCNIKPPCXBYKPKOYCYKPPJDIXBYXCNHDEKIUCIODEFYBCIZBYHCDYXDOOCNKRCKIRIKYDNKPPJZBYHCDYKIJOCNYCXYNBKPKIBIRBQIKIYUNCZRHKIQOYZCOBTOCPBUBYCNOCIKHKOYBPJVDBPYOUKXXCPRBIXNCIYCXIKIUJOPKZUCDNYOYHBOIKIUJBOKYCZIICYKZCEKIKIRNKIOKUWOKPCUKPLCDNIKPKRBOQDOYBIQNBQHYZBIQNKQYHKYBOOBRBIQKQKBIOYBYDFKIRRCZIYHBOPKIRCXCDNOPCCYBIQHKOVNCDQHYRCUWOOHCFOKIRXKNEOYCKSBNYDKPOYKIROYBPPKSCBRYNKIOPKYBCIVJKRKBN"
a = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"]
counter = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
total = 0

# workbook = xlsxwriter.Workbook('printout1.xlsx')
# worksheet = workbook.add_worksheet()

for x in xrange(0,len(plain)):
	for i in xrange(0,len(a)):
		if plain[x] == a[i]:
			counter[i] = counter[i]+1
			total = total +1
for x in xrange(0,len(counter)):
	key = counter[x]
	key2 = a[x]
	i = x -1
	while i >= 0 and counter[i] > key:
		counter[i +1] = counter[i]
		a[i+1] = a[i]
		i = i -1
	counter[i+1] = key
	a[i+1] = key2
# for x in xrange(0,len(counter)):
# 	counter[x]= counter[x]/1200.0
# 	worksheet.write(x+1,0,a[x])
# 	worksheet.write(x+1,1,counter[x])
# workbook.close()
empty = ""
a.reverse()

test =['K','C','B','I','Y','O','N','P','D','R','U','X','Q','H','J','E','V','F','Z','W','S','T','L','G','M','A']
test2=["A","O","I","N","T","S","R","L","U","D","C","F","G","H","Y","M","B","P","W","K","V","X","J","Q","-","-"]

for j in xrange(0,len(plain)):

	for x in xrange(0,len(a)):

		if str(plain[j]) == (a[x]):
			empty = empty+ test2[x]			

print empty


